library(tidyr)
library(proxy)
source('read_trips.R')
source('rot_all.R')
df = read_trips(getwd())
df2 = rot_all(df)
#df2$dist = sqrt((df2$x^2+df2$y^2))
df.x = data.frame(time = df2$time, x = df2$x, trip = df2$trip)
df.y = data.frame(time = df2$time, y = df2$y, trip = df2$trip)
df.x = spread(df.x,trip, x)
df.y = spread(df.y, trip, y)
dist.mat.y = dist(t(as.matrix(df.y[,-1])), method='cosine')
dist.mat.x = dist(t(as.matrix(df.x[,-1])), method='cosine')
dist.mat.y = as.matrix(dist.mat.y)
dist.mat.x = as.matrix(dist.mat.y)
